-- WTFCode PostgreSQL production schema for a fresh Supabase project.
-- Canonical bootstrap: paste this entire file into the Supabase SQL Editor once.

CREATE TABLE IF NOT EXISTS schema_migrations (
    version VARCHAR(100) PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(190) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_email_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(140) NOT NULL,
    repository_url VARCHAR(500) NOT NULL,
    local_path VARCHAR(500) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'cloning', 'scanning', 'ready', 'failed')),
    stack_json JSONB,
    overview TEXT,
    last_scan_at TIMESTAMPTZ,
    last_error VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT projects_user_repository_unique UNIQUE (user_id, repository_url)
);
CREATE INDEX IF NOT EXISTS projects_user_updated_index ON projects(user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS project_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    path VARCHAR(500) NOT NULL,
    language VARCHAR(50) NOT NULL,
    file_size INTEGER NOT NULL CHECK (file_size >= 0),
    line_count INTEGER NOT NULL DEFAULT 0 CHECK (line_count >= 0),
    content_hash CHAR(64) NOT NULL,
    role_name VARCHAR(80) NOT NULL DEFAULT 'source',
    plain_summary TEXT,
    symbols_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT project_files_project_path_unique UNIQUE (project_id, path)
);
CREATE INDEX IF NOT EXISTS project_files_project_role_index ON project_files(project_id, role_name);
CREATE INDEX IF NOT EXISTS project_files_project_hash_index ON project_files(project_id, content_hash);

CREATE TABLE IF NOT EXISTS project_dependencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    source_file_id BIGINT NOT NULL REFERENCES project_files(id) ON DELETE CASCADE,
    target_file_id BIGINT REFERENCES project_files(id) ON DELETE SET NULL,
    target_path VARCHAR(500) NOT NULL,
    relationship_type VARCHAR(20) NOT NULL DEFAULT 'imports' CHECK (relationship_type IN ('imports', 'requires', 'uses')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT project_dependency_unique UNIQUE (source_file_id, target_path, relationship_type)
);
CREATE INDEX IF NOT EXISTS project_dependencies_target_index ON project_dependencies(target_file_id);
CREATE INDEX IF NOT EXISTS project_dependencies_project_index ON project_dependencies(project_id, source_file_id);

CREATE TABLE IF NOT EXISTS architecture_nodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    node_key VARCHAR(100) NOT NULL,
    node_type VARCHAR(50) NOT NULL,
    label VARCHAR(160) NOT NULL,
    plain_explanation TEXT NOT NULL,
    evidence_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT architecture_nodes_project_key_unique UNIQUE (project_id, node_key)
);

CREATE TABLE IF NOT EXISTS architecture_edges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    from_node_id BIGINT NOT NULL REFERENCES architecture_nodes(id) ON DELETE CASCADE,
    to_node_id BIGINT NOT NULL REFERENCES architecture_nodes(id) ON DELETE CASCADE,
    relationship_label VARCHAR(160) NOT NULL,
    evidence_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT architecture_edge_unique UNIQUE (project_id, from_node_id, to_node_id, relationship_label)
);

CREATE TABLE IF NOT EXISTS scan_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    commit_sha VARCHAR(64),
    analysis_version VARCHAR(20) NOT NULL DEFAULT 'v1',
    analysis_profile VARCHAR(20) NOT NULL DEFAULT 'quick',
    files_scanned INTEGER NOT NULL DEFAULT 0 CHECK (files_scanned >= 0),
    findings_count INTEGER NOT NULL DEFAULT 0 CHECK (findings_count >= 0),
    analyzer_stats_json JSONB,
    engine_status_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS scan_runs_project_created_index ON scan_runs(project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS scan_runs_project_version_index ON scan_runs(project_id, analysis_version, created_at DESC);

CREATE TABLE IF NOT EXISTS scan_findings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    scan_run_id BIGINT REFERENCES scan_runs(id) ON DELETE CASCADE,
    severity VARCHAR(20) NOT NULL DEFAULT 'info' CHECK (severity IN ('info', 'attention', 'risk')),
    finding_type VARCHAR(80) NOT NULL,
    title VARCHAR(255) NOT NULL,
    plain_explanation TEXT NOT NULL,
    file_path VARCHAR(500),
    evidence_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS scan_findings_project_severity_index ON scan_findings(project_id, severity);
CREATE INDEX IF NOT EXISTS scan_findings_scan_type_index ON scan_findings(scan_run_id, finding_type);

CREATE TABLE IF NOT EXISTS analysis_provider_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    scan_run_id BIGINT NOT NULL REFERENCES scan_runs(id) ON DELETE CASCADE,
    engine_id VARCHAR(80) NOT NULL,
    engine_version VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('success', 'partial', 'unavailable', 'failed')),
    duration_ms INTEGER NOT NULL DEFAULT 0 CHECK (duration_ms >= 0),
    symbols_count INTEGER NOT NULL DEFAULT 0 CHECK (symbols_count >= 0),
    relationships_count INTEGER NOT NULL DEFAULT 0 CHECK (relationships_count >= 0),
    routes_count INTEGER NOT NULL DEFAULT 0 CHECK (routes_count >= 0),
    packages_count INTEGER NOT NULL DEFAULT 0 CHECK (packages_count >= 0),
    findings_count INTEGER NOT NULL DEFAULT 0 CHECK (findings_count >= 0),
    message VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT analysis_provider_runs_scan_engine_unique UNIQUE (scan_run_id, engine_id)
);
CREATE INDEX IF NOT EXISTS analysis_provider_runs_project_status_index ON analysis_provider_runs(project_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS package_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    scan_run_id BIGINT NOT NULL REFERENCES scan_runs(id) ON DELETE CASCADE,
    package_name VARCHAR(255) NOT NULL,
    package_version VARCHAR(160) NOT NULL DEFAULT '',
    ecosystem VARCHAR(80) NOT NULL DEFAULT 'unknown',
    purl VARCHAR(700),
    classification VARCHAR(20) NOT NULL DEFAULT 'detected' CHECK (classification IN ('declared', 'resolved', 'detected')),
    licenses_json JSONB,
    locations_json JSONB,
    providers_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT package_inventory_scan_identity_unique UNIQUE (scan_run_id, ecosystem, package_name, package_version)
);
CREATE INDEX IF NOT EXISTS package_inventory_project_classification_index ON package_inventory(project_id, classification, package_name);

CREATE TABLE IF NOT EXISTS code_symbols (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    scan_run_id BIGINT NOT NULL REFERENCES scan_runs(id) ON DELETE CASCADE,
    file_id BIGINT NOT NULL REFERENCES project_files(id) ON DELETE CASCADE,
    parent_symbol_id BIGINT REFERENCES code_symbols(id) ON DELETE SET NULL,
    symbol_key CHAR(64) NOT NULL,
    symbol_type VARCHAR(50) NOT NULL,
    language VARCHAR(40) NOT NULL,
    name VARCHAR(255) NOT NULL,
    qualified_name VARCHAR(700) NOT NULL,
    signature_text VARCHAR(1000),
    visibility VARCHAR(20) NOT NULL DEFAULT 'unknown' CHECK (visibility IN ('public', 'protected', 'private', 'package', 'unknown')),
    is_exported BOOLEAN NOT NULL DEFAULT FALSE,
    start_line INTEGER NOT NULL CHECK (start_line > 0),
    end_line INTEGER NOT NULL CHECK (end_line > 0),
    confidence VARCHAR(20) NOT NULL DEFAULT 'medium' CHECK (confidence IN ('high', 'medium', 'low')),
    metadata_json JSONB,
    provenance_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT code_symbols_scan_key_unique UNIQUE (scan_run_id, symbol_key)
);
CREATE INDEX IF NOT EXISTS code_symbols_project_type_index ON code_symbols(project_id, symbol_type, name);
CREATE INDEX IF NOT EXISTS code_symbols_file_line_index ON code_symbols(file_id, start_line);
CREATE INDEX IF NOT EXISTS code_symbols_qualified_index ON code_symbols(project_id, qualified_name);

CREATE TABLE IF NOT EXISTS symbol_relationships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    scan_run_id BIGINT NOT NULL REFERENCES scan_runs(id) ON DELETE CASCADE,
    source_symbol_id BIGINT REFERENCES code_symbols(id) ON DELETE CASCADE,
    target_symbol_id BIGINT REFERENCES code_symbols(id) ON DELETE CASCADE,
    target_external_name VARCHAR(700),
    evidence_file_id BIGINT NOT NULL REFERENCES project_files(id) ON DELETE CASCADE,
    relationship_type VARCHAR(50) NOT NULL,
    confidence VARCHAR(20) NOT NULL DEFAULT 'medium' CHECK (confidence IN ('high', 'medium', 'low')),
    evidence_line_start INTEGER,
    evidence_line_end INTEGER,
    evidence_excerpt VARCHAR(1000),
    metadata_json JSONB,
    provenance_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS symbol_relationships_source_type_index ON symbol_relationships(source_symbol_id, relationship_type);
CREATE INDEX IF NOT EXISTS symbol_relationships_target_type_index ON symbol_relationships(target_symbol_id, relationship_type);
CREATE INDEX IF NOT EXISTS symbol_relationships_project_external_index ON symbol_relationships(project_id, target_external_name);
CREATE INDEX IF NOT EXISTS symbol_relationships_evidence_index ON symbol_relationships(evidence_file_id, evidence_line_start);

CREATE TABLE IF NOT EXISTS code_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    scan_run_id BIGINT NOT NULL REFERENCES scan_runs(id) ON DELETE CASCADE,
    file_id BIGINT NOT NULL REFERENCES project_files(id) ON DELETE CASCADE,
    handler_symbol_id BIGINT REFERENCES code_symbols(id) ON DELETE SET NULL,
    route_key CHAR(64) NOT NULL,
    framework VARCHAR(50) NOT NULL,
    http_method VARCHAR(20) NOT NULL,
    route_path VARCHAR(700) NOT NULL,
    route_name VARCHAR(255),
    middleware_json JSONB,
    confidence VARCHAR(20) NOT NULL DEFAULT 'medium' CHECK (confidence IN ('high', 'medium', 'low')),
    evidence_line INTEGER NOT NULL CHECK (evidence_line > 0),
    metadata_json JSONB,
    provenance_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT code_routes_scan_key_unique UNIQUE (scan_run_id, route_key)
);
CREATE INDEX IF NOT EXISTS code_routes_project_path_index ON code_routes(project_id, route_path);
CREATE INDEX IF NOT EXISTS code_routes_handler_index ON code_routes(handler_symbol_id);

CREATE TABLE IF NOT EXISTS learning_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    lesson_key VARCHAR(120) NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT learning_progress_unique UNIQUE (user_id, project_id, lesson_key)
);
CREATE INDEX IF NOT EXISTS learning_progress_project_user_index ON learning_progress(project_id, user_id);

CREATE TABLE IF NOT EXISTS change_guard_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    phase VARCHAR(20) NOT NULL CHECK (phase IN ('before', 'after')),
    label VARCHAR(180) NOT NULL DEFAULT '',
    intended_change VARCHAR(500) NOT NULL DEFAULT '',
    commit_sha VARCHAR(64),
    scan_run_id BIGINT REFERENCES scan_runs(id) ON DELETE SET NULL,
    snapshot_json JSONB NOT NULL,
    fingerprint CHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS change_guard_project_created_index ON change_guard_snapshots(project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS change_guard_project_phase_index ON change_guard_snapshots(project_id, phase, created_at DESC);

CREATE TABLE IF NOT EXISTS analysis_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    analysis_profile VARCHAR(20) NOT NULL,
    state VARCHAR(20) NOT NULL DEFAULT 'queued' CHECK (state IN ('queued', 'running', 'completed', 'partial', 'failed')),
    commit_sha VARCHAR(64),
    previous_commit_sha VARCHAR(64),
    changed_paths_json JSONB,
    error_message VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS analysis_jobs_project_created_index ON analysis_jobs(project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS analysis_jobs_state_created_index ON analysis_jobs(state, created_at);

CREATE TABLE IF NOT EXISTS analysis_job_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES analysis_jobs(id) ON DELETE CASCADE,
    provider_id VARCHAR(80) NOT NULL,
    provider_version VARCHAR(100) NOT NULL,
    state VARCHAR(20) NOT NULL CHECK (state IN ('queued', 'running', 'completed', 'partial', 'failed')),
    cache_hit BOOLEAN NOT NULL DEFAULT FALSE,
    incremental BOOLEAN NOT NULL DEFAULT FALSE,
    files_analyzed INTEGER NOT NULL DEFAULT 0 CHECK (files_analyzed >= 0),
    duration_ms INTEGER NOT NULL DEFAULT 0 CHECK (duration_ms >= 0),
    message VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,
    CONSTRAINT analysis_job_steps_job_provider_unique UNIQUE (job_id, provider_id)
);
CREATE INDEX IF NOT EXISTS analysis_job_steps_state_index ON analysis_job_steps(state, created_at);

CREATE TABLE IF NOT EXISTS engine_disagreements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    scan_run_id BIGINT NOT NULL REFERENCES scan_runs(id) ON DELETE CASCADE,
    fact_identity CHAR(64) NOT NULL,
    fact_type VARCHAR(80) NOT NULL,
    provider_results_json JSONB NOT NULL,
    resolution VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT engine_disagreements_scan_fact_unique UNIQUE (scan_run_id, fact_identity)
);
CREATE INDEX IF NOT EXISTS engine_disagreements_project_type_index ON engine_disagreements(project_id, fact_type);

CREATE TABLE IF NOT EXISTS sessions (
    session_id VARCHAR(128) PRIMARY KEY,
    payload TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS sessions_expires_index ON sessions(expires_at);

CREATE TABLE IF NOT EXISTS login_attempts (
    attempt_key CHAR(64) PRIMARY KEY,
    failures INTEGER NOT NULL DEFAULT 0 CHECK (failures >= 0),
    first_attempt_at TIMESTAMPTZ NOT NULL,
    locked_until TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS login_attempts_locked_index ON login_attempts(locked_until);

CREATE TABLE IF NOT EXISTS provider_cache_entries (
    cache_key CHAR(64) PRIMARY KEY,
    provider_id VARCHAR(80) NOT NULL,
    provider_version VARCHAR(100) NOT NULL,
    analysis_version VARCHAR(20) NOT NULL,
    result_json JSONB NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS provider_cache_entries_expires_index ON provider_cache_entries(expires_at);

CREATE OR REPLACE FUNCTION wtfcode_touch_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION wtfcode_touch_updated_at() FROM PUBLIC;

DROP TRIGGER IF EXISTS users_touch_updated_at ON users;
CREATE TRIGGER users_touch_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION wtfcode_touch_updated_at();
DROP TRIGGER IF EXISTS projects_touch_updated_at ON projects;
CREATE TRIGGER projects_touch_updated_at BEFORE UPDATE ON projects FOR EACH ROW EXECUTE FUNCTION wtfcode_touch_updated_at();

-- Backend-only model: browser-facing Supabase Data API roles receive no privileges.
DO $$
DECLARE role_name TEXT;
BEGIN
    FOREACH role_name IN ARRAY ARRAY['anon', 'authenticated', 'service_role'] LOOP
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
            EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA public FROM %I', role_name);
            EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM %I', role_name);
            EXECUTE format('REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM %I', role_name);
        END IF;
    END LOOP;
END;
$$;

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_dependencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE architecture_nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE architecture_edges ENABLE ROW LEVEL SECURITY;
ALTER TABLE scan_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE scan_findings ENABLE ROW LEVEL SECURITY;
ALTER TABLE analysis_provider_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE package_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE code_symbols ENABLE ROW LEVEL SECURITY;
ALTER TABLE symbol_relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE code_routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE change_guard_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE analysis_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE analysis_job_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE engine_disagreements ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE login_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE provider_cache_entries ENABLE ROW LEVEL SECURITY;

INSERT INTO schema_migrations(version) VALUES ('202608200001_initial_production') ON CONFLICT (version) DO NOTHING;
