<?php

declare(strict_types=1);

require_once __DIR__ . '/../bootstrap.php';
if (Auth::check()) redirect('dashboard.php');
$pageTitle = 'Know what your AI built';
require __DIR__ . '/../views/header.php';
?>
<section class="landing-hero">
    <div class="landing-copy"><p class="landing-kicker">Evidence-first repository understanding</p><h1>Know what your AI actually built.</h1><p>WTFCode turns a GitHub repository into a readable map of its stack, connected files, change risk, and the parts worth learning before the next prompt.</p><div class="hero-actions"><a class="button button-primary" href="<?= e(url('register.php')) ?>">Map a repository</a><a class="button button-secondary" href="#how-it-works">How it works</a></div><p class="hero-note">Public GitHub repositories only. Static analysis only. No source code is sent to an AI service.</p></div>
    <div class="hero-evidence" aria-label="WTFCode product interface preview"><div class="evidence-bar"><span>repository map</span><span>static evidence</span></div><div class="evidence-body"><p class="signal-label">Actual WTFCode interface</p><h2>What the scanner found</h2><div class="architecture-nodes preview-nodes"><?php $architectureNode = ['node_type' => 'frontend', 'label' => 'Next.js frontend', 'plain_explanation' => 'Browser screens were detected from route and configuration files.']; $architectureHref = '#how-it-works'; require __DIR__ . '/../views/architecture-node.php'; ?><?php $architectureNode = ['node_type' => 'auth', 'label' => 'Authentication', 'plain_explanation' => 'Sign-in and request protection clues are available to inspect.']; $architectureHref = '#security'; require __DIR__ . '/../views/architecture-node.php'; ?></div><div class="evidence-callout"><strong>Before you edit</strong><p>Open confirmed blast radius first, then review the Git change set for configuration or data impact.</p></div></div></div>
</section>
<section class="landing-section story-section" id="how-it-works"><div class="section-intro"><p class="landing-kicker">From repo to understanding</p><h2>Stop guessing which file does what.</h2><p>Import a repository and get explanations tied to the source structure and relationships that actually exist.</p></div><div class="story-grid"><article><strong>01</strong><h3>Read the structure</h3><p>WTFCode identifies frameworks, routes, configuration, authentication clues, data layers, and deployment files.</p></article><article><strong>02</strong><h3>Follow connections</h3><p>Static imports and includes become a dependency map with direct and transitive blast radius.</p></article><article><strong>03</strong><h3>Change with context</h3><p>Build a bounded prompt, then review its Git change set against the affected systems.</p></article></div></section>
<section class="landing-section feature-split"><div><p class="landing-kicker">Learn your own app</p><h2>Your project becomes the lesson.</h2><p>Learn from the architecture that was actually detected, track what you explored, and keep each next change grounded in evidence.</p><a href="<?= e(url('register.php')) ?>">Create your workspace</a></div><div class="feature-list"><div><span>Evidence map</span><p>Click a system to see the exact scanned files that supported its detection.</p></div><div><span>Honest blast radius</span><p>Direct and transitive import chains are marked as confirmed static evidence; system-level effects stay labelled as inferred.</p></div><div><span>Git review</span><p>Compare real commits and group the files that changed, with sensitive paths called out for review.</p></div></div></section>
<section class="landing-section security-section" id="security"><p class="landing-kicker">Privacy by design</p><h2>Analysis, not surveillance.</h2><div class="security-points"><p>Public GitHub URLs are restricted to github.com.</p><p>Repository clones remain outside the public web directory.</p><p>WTFCode stores metadata and evidence, not source-file contents.</p><p>No external AI API is called by this MVP.</p></div></section>
<section class="landing-cta"><div><h2>Build fast. Stay in control.</h2><p>Start by understanding one repository end to end.</p></div><a class="button button-light" href="<?= e(url('register.php')) ?>">Start free</a></section>
<?php require __DIR__ . '/../views/footer.php'; ?>
