<?php

declare(strict_types=1);

require_once __DIR__ . '/../bootstrap.php';
if (Auth::check()) redirect('dashboard.php');
$pageTitle = 'Know what your AI built';
require __DIR__ . '/../views/header.php';
?>
<section class="landing-hero">
    <div class="landing-copy"><p class="landing-kicker">Repository intelligence for AI-built software</p><h1>Know the code.<br>Change it safely.</h1><p>Turn a public GitHub repository into an evidence-backed map of its architecture, dependencies, routes, data, and change risk.</p><div class="hero-actions"><a class="button button-primary" href="<?= e(url('register.php')) ?>">Analyze a repository</a><a class="button button-secondary" href="#how-it-works">See how it works</a></div><p class="hero-note">Static analysis. Temporary clones. No source files retained.</p></div>
    <figure class="product-shot"><div class="product-shot-bar"><span><i></i><i></i><i></i></span><b>Project overview</b><em>Live product</em></div><img src="<?= e(url('assets/images/product-overview.png')) ?>" width="1440" height="900" alt="WTFCode project overview showing an analyzed Laravel repository, symbol and route counts, analysis status, and project navigation." loading="eager"><figcaption>Real WTFCode analysis, captured from the production interface.</figcaption></figure>
</section>
<section class="landing-section story-section" id="how-it-works"><div class="section-intro"><p class="landing-kicker">From repo to understanding</p><h2>Stop guessing which file does what.</h2><p>Import a repository and get explanations tied to the source structure and relationships that actually exist.</p></div><div class="story-grid"><article><strong>01</strong><h3>Read the structure</h3><p>WTFCode identifies frameworks, routes, configuration, authentication clues, data layers, and deployment files.</p></article><article><strong>02</strong><h3>Follow connections</h3><p>Static imports and includes become a dependency map with direct and transitive blast radius.</p></article><article><strong>03</strong><h3>Change with context</h3><p>Build a bounded prompt, then review its Git change set against the affected systems.</p></article></div></section>
<section class="landing-section feature-split"><div><p class="landing-kicker">Learn your own app</p><h2>Your project becomes the lesson.</h2><p>Learn from the architecture that was actually detected, track what you explored, and keep each next change grounded in evidence.</p><a href="<?= e(url('register.php')) ?>">Create your workspace</a></div><div class="feature-list"><div><span>Evidence map</span><p>Click a system to see the exact scanned files that supported its detection.</p></div><div><span>Honest blast radius</span><p>Direct and transitive import chains are marked as confirmed static evidence; system-level effects stay labelled as inferred.</p></div><div><span>Git review</span><p>Compare real commits and group the files that changed, with sensitive paths called out for review.</p></div></div></section>
<section class="landing-section security-section" id="security"><p class="landing-kicker">Privacy by design</p><h2>Analysis, not surveillance.</h2><div class="security-points"><p>Public GitHub URLs are restricted to github.com.</p><p>Hosted clones are temporary and removed after each scan.</p><p>Complete source files are not retained; bounded signatures and evidence excerpts can be stored.</p><p>External explanation providers are used only when an operator configures one.</p></div></section>
<section class="landing-cta"><div><h2>Build fast. Stay in control.</h2><p>Start by understanding one repository end to end.</p></div><a class="button button-light" href="<?= e(url('register.php')) ?>">Start free</a></section>
<?php require __DIR__ . '/../views/footer.php'; ?>
