<?php

declare(strict_types=1);

require_once __DIR__ . '/../bootstrap.php';
Auth::requireLogin();
$projectId = filter_var($_GET['project'] ?? null, FILTER_VALIDATE_INT);
$symbolId = filter_var($_GET['id'] ?? null, FILTER_VALIDATE_INT);
$project = $projectId === false || $projectId === null ? null : Project::findForUser((int) $projectId, Auth::id());
$symbol = $project === null || $symbolId === false || $symbolId === null ? null : SymbolRepository::symbol((int) $project['id'], (int) $symbolId);
if ($project === null || $symbol === null) { http_response_code(404); exit('Symbol not found.'); }
$outgoing = SymbolRepository::relationships((int) $project['id'], (int) $symbol['id']);
$incoming = SymbolRepository::relationships((int) $project['id'], (int) $symbol['id'], 'incoming');
$blast = BlastRadiusService::forSymbol((int) $project['id'], (int) $symbol['id']);
$excerpt = SourceReader::excerpt($project, (string) $symbol['path'], (int) $symbol['start_line'], (int) $symbol['end_line']);
$pageTitle = $symbol['name'];
$activePage = 'dashboard';
$activeProjectSection = 'symbols';
require __DIR__ . '/../views/header.php';
?>
<section class="app-shell v2-shell symbol-detail-page">
    <div class="breadcrumb"><a href="<?= e(url('project.php?id=' . (int) $project['id'])) ?>"><?= e($project['name']) ?></a><span>/</span><a href="<?= e(url('symbols.php?id=' . (int) $project['id'])) ?>">Symbols</a><span>/</span><span><?= e($symbol['name']) ?></span></div>
    <div class="symbol-hero"><div><div class="symbol-label-row"><span><?= e(str_replace('_', ' ', $symbol['symbol_type'])) ?></span><span class="confidence <?= e($symbol['confidence']) ?>"><?= e($symbol['confidence']) ?> confidence</span></div><h1><?= e($symbol['name']) ?></h1><code><?= e($symbol['qualified_name']) ?></code><p><?= e($symbol['path']) ?>, lines <?= (int) $symbol['start_line'] ?>-<?= (int) $symbol['end_line'] ?><?= $symbol['parent_name'] ? ', inside ' . e($symbol['parent_name']) : '' ?></p></div><div class="risk-callout <?= e($blast['risk']) ?>"><span>Edit risk</span><strong><?= e($blast['risk']) ?></strong><small>Based on confirmed and medium-confidence graph reach.</small></div></div>
    <?php require __DIR__ . '/../views/project-nav.php'; ?>
    <section class="symbol-summary-grid"><div><span>Incoming</span><strong><?= count($incoming) ?></strong><small>callers and consumers</small></div><div><span>Outgoing</span><strong><?= count($outgoing) ?></strong><small>calls and dependencies</small></div><div><span>Affected files</span><strong><?= count($blast['files']) ?></strong><small>within six hops</small></div><div><span>Routes</span><strong><?= count($blast['routes']) ?></strong><small>linked handlers</small></div><div><span>Data</span><strong><?= count($blast['tables']) ?></strong><small>tables, models, schemas</small></div></section>
    <section class="symbol-layout">
        <article class="panel source-panel"><div class="section-row"><div><h2>Source evidence</h2><p>Read-only excerpt from the private repository clone.</p></div><a href="<?= e(url('file.php?project=' . (int) $project['id'] . '&id=' . (int) $symbol['file_id'])) ?>">Open file analysis</a></div><?php if ($excerpt === null): ?><div class="empty-state-v2"><strong>Source excerpt unavailable.</strong><p>The clone moved, the file exceeded the safe limit, or the path no longer resolves inside the repository.</p></div><?php else: ?><pre class="source-excerpt" tabindex="0"><?php foreach ($excerpt['lines'] as $sourceLine): ?><span class="<?= $sourceLine['number'] >= (int) $symbol['start_line'] && $sourceLine['number'] <= (int) $symbol['end_line'] ? 'is-symbol-line' : '' ?>"><b><?= $sourceLine['number'] ?></b><code><?= e($sourceLine['text']) ?></code></span><?php endforeach; ?></pre><?php endif; ?></article>
        <aside class="panel before-edit-v2"><h2>Before you edit</h2><ol><?php foreach ($blast['checklist'] as $item): ?><li><?= e($item) ?></li><?php endforeach; ?></ol><?php if ($blast['unknowns'] !== []): ?><p class="uncertainty-note"><?= count($blast['unknowns']) ?> unresolved target<?= count($blast['unknowns']) === 1 ? '' : 's' ?> need manual verification.</p><?php endif; ?></aside>
    </section>
    <section class="relationship-columns">
        <article class="panel"><div class="section-row"><div><h2>What this symbol reaches</h2><p>Outgoing edges with source-line evidence.</p></div><span class="count-mark"><?= count($outgoing) ?></span></div><?php if ($outgoing === []): ?><div class="empty-state-v2"><strong>No outgoing edge detected.</strong><p>Dynamic calls can still exist.</p></div><?php else: ?><div class="relationship-list"><?php foreach ($outgoing as $edge): ?><?php $targetLabel = $edge['target_name'] ?: $edge['target_external_name']; ?><?php if ($edge['target_symbol_id']): ?><a href="<?= e(url('symbol.php?project=' . (int) $project['id'] . '&id=' . (int) $edge['target_symbol_id'])) ?>"><?php else: ?><div><?php endif; ?><span><?= e($edge['relationship_type']) ?></span><strong><?= e($targetLabel) ?></strong><small><?= e($edge['evidence_path']) ?>:<?= (int) $edge['evidence_line_start'] ?>, <?= e($edge['confidence']) ?> confidence</small><?php if ($edge['target_symbol_id']): ?></a><?php else: ?></div><?php endif; ?><?php endforeach; ?></div><?php endif; ?></article>
        <article class="panel"><div class="section-row"><div><h2>What reaches this symbol</h2><p>Direct incoming consumers.</p></div><span class="count-mark"><?= count($incoming) ?></span></div><?php if ($incoming === []): ?><div class="empty-state-v2"><strong>No incoming edge detected.</strong><p>This can be an entry point, unused code, or a dynamically referenced symbol.</p></div><?php else: ?><div class="relationship-list"><?php foreach ($incoming as $edge): ?><a href="<?= e(url('symbol.php?project=' . (int) $project['id'] . '&id=' . (int) $edge['source_symbol_id'])) ?>"><span><?= e($edge['relationship_type']) ?></span><strong><?= e($edge['source_name']) ?></strong><small><?= e($edge['evidence_path']) ?>:<?= (int) $edge['evidence_line_start'] ?>, <?= e($edge['confidence']) ?> confidence</small></a><?php endforeach; ?></div><?php endif; ?></article>
    </section>
    <section class="panel blast-panel"><div class="section-row"><div><h2>Symbol blast radius</h2><p>Direct and transitive consumers, affected routes, and data boundaries.</p></div><span class="risk-text <?= e($blast['risk']) ?>"><?= e($blast['risk']) ?> risk</span></div><div class="blast-groups"><div><h3>Direct consumers</h3><?php if ($blast['direct'] === []): ?><p>None detected.</p><?php else: ?><?php foreach ($blast['direct'] as $item): ?><a href="<?= e(url('symbol.php?project=' . (int) $project['id'] . '&id=' . (int) $item['id'])) ?>"><?= e($item['name']) ?><small><?= e($item['path']) ?>, <?= e($item['relationship']) ?></small></a><?php endforeach; ?><?php endif; ?></div><div><h3>Transitive consumers</h3><?php if ($blast['transitive'] === []): ?><p>None detected within six hops.</p><?php else: ?><?php foreach (array_slice($blast['transitive'], 0, 30) as $item): ?><a href="<?= e(url('symbol.php?project=' . (int) $project['id'] . '&id=' . (int) $item['id'])) ?>"><?= e($item['name']) ?><small><?= e($item['path']) ?>, <?= (int) $item['depth'] ?> hops</small></a><?php endforeach; ?><?php endif; ?></div><div><h3>Routes and data</h3><?php foreach ($blast['routes'] as $route): ?><a href="<?= e(url('routes.php?id=' . (int) $project['id'] . '&q=' . urlencode($route['route_path']))) ?>"><?= e($route['http_method'] . ' ' . $route['route_path']) ?><small><?= e($route['framework']) ?></small></a><?php endforeach; ?><?php foreach ($blast['tables'] as $table): ?><a href="<?= e(url('symbol.php?project=' . (int) $project['id'] . '&id=' . (int) $table['id'])) ?>"><?= e($table['name']) ?><small><?= e($table['type']) ?></small></a><?php endforeach; ?><?php if ($blast['routes'] === [] && $blast['tables'] === []): ?><p>No linked route or data boundary detected.</p><?php endif; ?></div></div></section>
</section>
<?php require __DIR__ . '/../views/footer.php'; ?>
