-- WTFCode now uses PostgreSQL as its canonical production database.
-- Apply ../supabase/production-schema.sql to a fresh PostgreSQL/Supabase database.
-- The numbered files in database/migrations are retained only for legacy MySQL installations.
