ALTER TABLE public.schema_migrations ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'wtfcode_app') THEN
    CREATE ROLE wtfcode_app
      NOLOGIN
      NOSUPERUSER
      NOCREATEDB
      NOCREATEROLE
      NOREPLICATION
      BYPASSRLS;
  ELSE
    ALTER ROLE wtfcode_app WITH
      NOLOGIN
      NOSUPERUSER
      NOCREATEDB
      NOCREATEROLE
      NOREPLICATION
      BYPASSRLS;
  END IF;
END
$$;

GRANT CONNECT ON DATABASE postgres TO wtfcode_app;
GRANT USAGE ON SCHEMA public TO wtfcode_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO wtfcode_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO wtfcode_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO wtfcode_app;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO wtfcode_app;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO wtfcode_app;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO wtfcode_app;

GRANT wtfcode_app TO postgres;;
