CREATE TABLE IF NOT EXISTS learning_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    lesson_key VARCHAR(120) NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT learning_progress_unique UNIQUE (user_id, project_id, lesson_key)
);
CREATE INDEX IF NOT EXISTS learning_progress_project_user_index ON learning_progress(project_id, user_id);

CREATE TABLE IF NOT EXISTS change_guard_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    phase VARCHAR(20) NOT NULL CHECK (phase IN ('before', 'after')),
    label VARCHAR(180) NOT NULL DEFAULT '',
    intended_change VARCHAR(500) NOT NULL DEFAULT '',
    commit_sha VARCHAR(64),
    scan_run_id BIGINT REFERENCES scan_runs(id) ON DELETE SET NULL,
    snapshot_json JSONB NOT NULL,
    fingerprint CHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS change_guard_project_created_index ON change_guard_snapshots(project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS change_guard_project_phase_index ON change_guard_snapshots(project_id, phase, created_at DESC);

CREATE TABLE IF NOT EXISTS analysis_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    analysis_profile VARCHAR(20) NOT NULL,
    state VARCHAR(20) NOT NULL DEFAULT 'queued' CHECK (state IN ('queued', 'running', 'completed', 'partial', 'failed')),
    commit_sha VARCHAR(64),
    previous_commit_sha VARCHAR(64),
    changed_paths_json JSONB,
    error_message VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS analysis_jobs_project_created_index ON analysis_jobs(project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS analysis_jobs_state_created_index ON analysis_jobs(state, created_at);

CREATE TABLE IF NOT EXISTS analysis_job_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES analysis_jobs(id) ON DELETE CASCADE,
    provider_id VARCHAR(80) NOT NULL,
    provider_version VARCHAR(100) NOT NULL,
    state VARCHAR(20) NOT NULL CHECK (state IN ('queued', 'running', 'completed', 'partial', 'failed')),
    cache_hit BOOLEAN NOT NULL DEFAULT FALSE,
    incremental BOOLEAN NOT NULL DEFAULT FALSE,
    files_analyzed INTEGER NOT NULL DEFAULT 0 CHECK (files_analyzed >= 0),
    duration_ms INTEGER NOT NULL DEFAULT 0 CHECK (duration_ms >= 0),
    message VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,
    CONSTRAINT analysis_job_steps_job_provider_unique UNIQUE (job_id, provider_id)
);
CREATE INDEX IF NOT EXISTS analysis_job_steps_state_index ON analysis_job_steps(state, created_at);

CREATE TABLE IF NOT EXISTS engine_disagreements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    scan_run_id BIGINT NOT NULL REFERENCES scan_runs(id) ON DELETE CASCADE,
    fact_identity CHAR(64) NOT NULL,
    fact_type VARCHAR(80) NOT NULL,
    provider_results_json JSONB NOT NULL,
    resolution VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT engine_disagreements_scan_fact_unique UNIQUE (scan_run_id, fact_identity)
);
CREATE INDEX IF NOT EXISTS engine_disagreements_project_type_index ON engine_disagreements(project_id, fact_type);

CREATE TABLE IF NOT EXISTS sessions (
    session_id VARCHAR(128) PRIMARY KEY,
    payload TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS sessions_expires_index ON sessions(expires_at);

CREATE TABLE IF NOT EXISTS login_attempts (
    attempt_key CHAR(64) PRIMARY KEY,
    failures INTEGER NOT NULL DEFAULT 0 CHECK (failures >= 0),
    first_attempt_at TIMESTAMPTZ NOT NULL,
    locked_until TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS login_attempts_locked_index ON login_attempts(locked_until);

CREATE TABLE IF NOT EXISTS provider_cache_entries (
    cache_key CHAR(64) PRIMARY KEY,
    provider_id VARCHAR(80) NOT NULL,
    provider_version VARCHAR(100) NOT NULL,
    analysis_version VARCHAR(20) NOT NULL,
    result_json JSONB NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS provider_cache_entries_expires_index ON provider_cache_entries(expires_at);;
