CREATE TABLE IF NOT EXISTS scan_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    commit_sha VARCHAR(64),
    analysis_version VARCHAR(20) NOT NULL DEFAULT 'v1',
    analysis_profile VARCHAR(20) NOT NULL DEFAULT 'quick',
    files_scanned INTEGER NOT NULL DEFAULT 0 CHECK (files_scanned >= 0),
    findings_count INTEGER NOT NULL DEFAULT 0 CHECK (findings_count >= 0),
    analyzer_stats_json JSONB,
    engine_status_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS scan_runs_project_created_index ON scan_runs(project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS scan_runs_project_version_index ON scan_runs(project_id, analysis_version, created_at DESC);

CREATE TABLE IF NOT EXISTS scan_findings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    scan_run_id BIGINT REFERENCES scan_runs(id) ON DELETE CASCADE,
    severity VARCHAR(20) NOT NULL DEFAULT 'info' CHECK (severity IN ('info', 'attention', 'risk')),
    finding_type VARCHAR(80) NOT NULL,
    title VARCHAR(255) NOT NULL,
    plain_explanation TEXT NOT NULL,
    file_path VARCHAR(500),
    evidence_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS scan_findings_project_severity_index ON scan_findings(project_id, severity);
CREATE INDEX IF NOT EXISTS scan_findings_scan_type_index ON scan_findings(scan_run_id, finding_type);

CREATE TABLE IF NOT EXISTS analysis_provider_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    scan_run_id BIGINT NOT NULL REFERENCES scan_runs(id) ON DELETE CASCADE,
    engine_id VARCHAR(80) NOT NULL,
    engine_version VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('success', 'partial', 'unavailable', 'failed')),
    duration_ms INTEGER NOT NULL DEFAULT 0 CHECK (duration_ms >= 0),
    symbols_count INTEGER NOT NULL DEFAULT 0 CHECK (symbols_count >= 0),
    relationships_count INTEGER NOT NULL DEFAULT 0 CHECK (relationships_count >= 0),
    routes_count INTEGER NOT NULL DEFAULT 0 CHECK (routes_count >= 0),
    packages_count INTEGER NOT NULL DEFAULT 0 CHECK (packages_count >= 0),
    findings_count INTEGER NOT NULL DEFAULT 0 CHECK (findings_count >= 0),
    message VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT analysis_provider_runs_scan_engine_unique UNIQUE (scan_run_id, engine_id)
);
CREATE INDEX IF NOT EXISTS analysis_provider_runs_project_status_index ON analysis_provider_runs(project_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS package_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    scan_run_id BIGINT NOT NULL REFERENCES scan_runs(id) ON DELETE CASCADE,
    package_name VARCHAR(255) NOT NULL,
    package_version VARCHAR(160) NOT NULL DEFAULT '',
    ecosystem VARCHAR(80) NOT NULL DEFAULT 'unknown',
    purl VARCHAR(700),
    classification VARCHAR(20) NOT NULL DEFAULT 'detected' CHECK (classification IN ('declared', 'resolved', 'detected')),
    licenses_json JSONB,
    locations_json JSONB,
    providers_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT package_inventory_scan_identity_unique UNIQUE (scan_run_id, ecosystem, package_name, package_version)
);
CREATE INDEX IF NOT EXISTS package_inventory_project_classification_index ON package_inventory(project_id, classification, package_name);

CREATE TABLE IF NOT EXISTS code_symbols (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    scan_run_id BIGINT NOT NULL REFERENCES scan_runs(id) ON DELETE CASCADE,
    file_id BIGINT NOT NULL REFERENCES project_files(id) ON DELETE CASCADE,
    parent_symbol_id BIGINT REFERENCES code_symbols(id) ON DELETE SET NULL,
    symbol_key CHAR(64) NOT NULL,
    symbol_type VARCHAR(50) NOT NULL,
    language VARCHAR(40) NOT NULL,
    name VARCHAR(255) NOT NULL,
    qualified_name VARCHAR(700) NOT NULL,
    signature_text VARCHAR(1000),
    visibility VARCHAR(20) NOT NULL DEFAULT 'unknown' CHECK (visibility IN ('public', 'protected', 'private', 'package', 'unknown')),
    is_exported BOOLEAN NOT NULL DEFAULT FALSE,
    start_line INTEGER NOT NULL CHECK (start_line > 0),
    end_line INTEGER NOT NULL CHECK (end_line > 0),
    confidence VARCHAR(20) NOT NULL DEFAULT 'medium' CHECK (confidence IN ('high', 'medium', 'low')),
    metadata_json JSONB,
    provenance_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT code_symbols_scan_key_unique UNIQUE (scan_run_id, symbol_key)
);
CREATE INDEX IF NOT EXISTS code_symbols_project_type_index ON code_symbols(project_id, symbol_type, name);
CREATE INDEX IF NOT EXISTS code_symbols_file_line_index ON code_symbols(file_id, start_line);
CREATE INDEX IF NOT EXISTS code_symbols_qualified_index ON code_symbols(project_id, qualified_name);

CREATE TABLE IF NOT EXISTS symbol_relationships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    scan_run_id BIGINT NOT NULL REFERENCES scan_runs(id) ON DELETE CASCADE,
    source_symbol_id BIGINT REFERENCES code_symbols(id) ON DELETE CASCADE,
    target_symbol_id BIGINT REFERENCES code_symbols(id) ON DELETE CASCADE,
    target_external_name VARCHAR(700),
    evidence_file_id BIGINT NOT NULL REFERENCES project_files(id) ON DELETE CASCADE,
    relationship_type VARCHAR(50) NOT NULL,
    confidence VARCHAR(20) NOT NULL DEFAULT 'medium' CHECK (confidence IN ('high', 'medium', 'low')),
    evidence_line_start INTEGER,
    evidence_line_end INTEGER,
    evidence_excerpt VARCHAR(1000),
    metadata_json JSONB,
    provenance_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS symbol_relationships_source_type_index ON symbol_relationships(source_symbol_id, relationship_type);
CREATE INDEX IF NOT EXISTS symbol_relationships_target_type_index ON symbol_relationships(target_symbol_id, relationship_type);
CREATE INDEX IF NOT EXISTS symbol_relationships_project_external_index ON symbol_relationships(project_id, target_external_name);
CREATE INDEX IF NOT EXISTS symbol_relationships_evidence_index ON symbol_relationships(evidence_file_id, evidence_line_start);

CREATE TABLE IF NOT EXISTS code_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    scan_run_id BIGINT NOT NULL REFERENCES scan_runs(id) ON DELETE CASCADE,
    file_id BIGINT NOT NULL REFERENCES project_files(id) ON DELETE CASCADE,
    handler_symbol_id BIGINT REFERENCES code_symbols(id) ON DELETE SET NULL,
    route_key CHAR(64) NOT NULL,
    framework VARCHAR(50) NOT NULL,
    http_method VARCHAR(20) NOT NULL,
    route_path VARCHAR(700) NOT NULL,
    route_name VARCHAR(255),
    middleware_json JSONB,
    confidence VARCHAR(20) NOT NULL DEFAULT 'medium' CHECK (confidence IN ('high', 'medium', 'low')),
    evidence_line INTEGER NOT NULL CHECK (evidence_line > 0),
    metadata_json JSONB,
    provenance_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT code_routes_scan_key_unique UNIQUE (scan_run_id, route_key)
);
CREATE INDEX IF NOT EXISTS code_routes_project_path_index ON code_routes(project_id, route_path);
CREATE INDEX IF NOT EXISTS code_routes_handler_index ON code_routes(handler_symbol_id);;
