-- WTFCode PostgreSQL production schema for a fresh Supabase project.
-- Canonical bootstrap: paste this entire file into the Supabase SQL Editor once.

CREATE TABLE IF NOT EXISTS schema_migrations (
    version VARCHAR(100) PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(190) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_email_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(140) NOT NULL,
    repository_url VARCHAR(500) NOT NULL,
    local_path VARCHAR(500) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'cloning', 'scanning', 'ready', 'failed')),
    stack_json JSONB,
    overview TEXT,
    last_scan_at TIMESTAMPTZ,
    last_error VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT projects_user_repository_unique UNIQUE (user_id, repository_url)
);
CREATE INDEX IF NOT EXISTS projects_user_updated_index ON projects(user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS project_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    path VARCHAR(500) NOT NULL,
    language VARCHAR(50) NOT NULL,
    file_size INTEGER NOT NULL CHECK (file_size >= 0),
    line_count INTEGER NOT NULL DEFAULT 0 CHECK (line_count >= 0),
    content_hash CHAR(64) NOT NULL,
    role_name VARCHAR(80) NOT NULL DEFAULT 'source',
    plain_summary TEXT,
    symbols_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT project_files_project_path_unique UNIQUE (project_id, path)
);
CREATE INDEX IF NOT EXISTS project_files_project_role_index ON project_files(project_id, role_name);
CREATE INDEX IF NOT EXISTS project_files_project_hash_index ON project_files(project_id, content_hash);

CREATE TABLE IF NOT EXISTS project_dependencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    source_file_id BIGINT NOT NULL REFERENCES project_files(id) ON DELETE CASCADE,
    target_file_id BIGINT REFERENCES project_files(id) ON DELETE SET NULL,
    target_path VARCHAR(500) NOT NULL,
    relationship_type VARCHAR(20) NOT NULL DEFAULT 'imports' CHECK (relationship_type IN ('imports', 'requires', 'uses')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT project_dependency_unique UNIQUE (source_file_id, target_path, relationship_type)
);
CREATE INDEX IF NOT EXISTS project_dependencies_target_index ON project_dependencies(target_file_id);
CREATE INDEX IF NOT EXISTS project_dependencies_project_index ON project_dependencies(project_id, source_file_id);

CREATE TABLE IF NOT EXISTS architecture_nodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    node_key VARCHAR(100) NOT NULL,
    node_type VARCHAR(50) NOT NULL,
    label VARCHAR(160) NOT NULL,
    plain_explanation TEXT NOT NULL,
    evidence_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT architecture_nodes_project_key_unique UNIQUE (project_id, node_key)
);

CREATE TABLE IF NOT EXISTS architecture_edges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    from_node_id BIGINT NOT NULL REFERENCES architecture_nodes(id) ON DELETE CASCADE,
    to_node_id BIGINT NOT NULL REFERENCES architecture_nodes(id) ON DELETE CASCADE,
    relationship_label VARCHAR(160) NOT NULL,
    evidence_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT architecture_edge_unique UNIQUE (project_id, from_node_id, to_node_id, relationship_label)
);
;
