DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'wtfcode_vercel') THEN
    CREATE ROLE wtfcode_vercel WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION INHERIT;
  ELSE
    ALTER ROLE wtfcode_vercel WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION INHERIT;
  END IF;
END
$$;
GRANT wtfcode_app TO wtfcode_vercel;
GRANT wtfcode_vercel TO postgres;;
