CREATE TABLE IF NOT EXISTS public.github_installations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    github_installation_id BIGINT NOT NULL CHECK (github_installation_id > 0),
    account_id BIGINT NOT NULL CHECK (account_id > 0),
    account_login VARCHAR(255) NOT NULL,
    account_type VARCHAR(40) NOT NULL,
    repository_selection VARCHAR(30) NOT NULL,
    permissions_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    suspended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT github_installations_user_installation_unique UNIQUE (user_id, github_installation_id)
);

CREATE INDEX IF NOT EXISTS github_installations_user_index ON public.github_installations(user_id, account_login);

ALTER TABLE public.projects
    ADD COLUMN IF NOT EXISTS github_installation_id BIGINT REFERENCES public.github_installations(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS github_repository_id BIGINT,
    ADD COLUMN IF NOT EXISTS github_repository_owner VARCHAR(255),
    ADD COLUMN IF NOT EXISTS github_repository_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS github_repository_visibility VARCHAR(20);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'projects_github_repository_pair_check' AND conrelid = 'public.projects'::regclass) THEN
    ALTER TABLE public.projects ADD CONSTRAINT projects_github_repository_pair_check CHECK (
        (github_installation_id IS NULL AND github_repository_id IS NULL)
        OR (github_installation_id IS NOT NULL AND github_repository_id IS NOT NULL AND github_repository_id > 0)
    );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'projects_github_visibility_check' AND conrelid = 'public.projects'::regclass) THEN
    ALTER TABLE public.projects ADD CONSTRAINT projects_github_visibility_check CHECK (github_repository_visibility IS NULL OR github_repository_visibility IN ('public', 'private', 'internal'));
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS projects_github_installation_index ON public.projects(github_installation_id);
CREATE INDEX IF NOT EXISTS projects_github_repository_index ON public.projects(github_repository_id);

DROP TRIGGER IF EXISTS github_installations_touch_updated_at ON public.github_installations;
CREATE TRIGGER github_installations_touch_updated_at BEFORE UPDATE ON public.github_installations FOR EACH ROW EXECUTE FUNCTION public.wtfcode_touch_updated_at();

ALTER TABLE public.github_installations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS wtfcode_backend_all ON public.github_installations;
CREATE POLICY wtfcode_backend_all ON public.github_installations FOR ALL TO wtfcode_app USING (true) WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.github_installations TO wtfcode_app;
GRANT USAGE, SELECT ON SEQUENCE public.github_installations_id_seq TO wtfcode_app;
REVOKE ALL ON public.github_installations FROM anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE public.github_installations_id_seq FROM anon, authenticated, service_role;
